package com.tonic.analysis.ssa.lower;

import com.tonic.analysis.ssa.cfg.ExceptionHandler;
import com.tonic.analysis.ssa.cfg.IRBlock;
import com.tonic.analysis.ssa.cfg.IRMethod;
import com.tonic.analysis.ssa.ir.*;
import com.tonic.analysis.ssa.type.*;
import com.tonic.analysis.ssa.value.*;
import com.tonic.parser.ClassFile;
import com.tonic.parser.ConstPool;
import com.tonic.parser.MethodEntry;
import com.tonic.parser.attribute.Attribute;
import com.tonic.parser.attribute.BootstrapMethodsAttribute;
import com.tonic.parser.attribute.table.BootstrapMethod;
import com.tonic.parser.constpool.*;
import com.tonic.type.AccessFlags;
import com.tonic.util.Opcode;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.*;

/**
 * Emits JVM bytecode from IR instructions.
 */
public class BytecodeEmitter {

    private final IRMethod method;
    private final ConstPool constPool;
    private final RegisterAllocator regAlloc;
    private final StackScheduler scheduler;

    private ByteArrayOutputStream bytecode;
    private DataOutputStream dos;
    private final Map<IRBlock, Integer> blockOffsets;
    private final Map<IRBlock, Integer> blockEndOffsets;
    private final List<PendingJump> pendingJumps;
    private int currentOffset;

    private final Set<SSAValue> stackResidentValues;
    /** Per-block register operand pushed at the block head so a condition's bound stays on the stack. */
    private final Map<IRBlock, SSAValue> blockHeadPreload;
    /** Values already pushed onto the stack ahead of their use (a head preload), to be skipped at the use. */
    private final Set<SSAValue> preloadedOnStack;
    private final Set<SSAValue> inlinedConstants;
    private final Map<SSAValue, Constant> inlinedConstantValue;
    /**
     * Caught-exception values captured at handler entry. The lift marks each handler block with a self-copy
     * of the value the JVM pushes onto the entry stack; this set drives the emitter to store that stack
     * value into the value's local (an {@code astore}) so a later use re-loads it correctly.
     */
    private final Set<SSAValue> handlerExceptionCaptures;

    /** Maps each {@code new} to its paired {@code <init>} so the pair emits {@code new; dup; args; invokespecial}. */
    private final Map<NewInstruction, InvokeInstruction> newToInit;
    private final Map<InvokeInstruction, NewInstruction> initToNew;

    // For fall-through optimization
    private IRBlock nextBlock;

    /**
     * Creates a new bytecode emitter.
     *
     * @param method the IR method to emit
     * @param constPool the constant pool
     * @param regAlloc the register allocator
     * @param scheduler the stack scheduler
     */
    public BytecodeEmitter(IRMethod method, ConstPool constPool, RegisterAllocator regAlloc, StackScheduler scheduler) {
        this.method = method;
        this.constPool = constPool;
        this.regAlloc = regAlloc;
        this.scheduler = scheduler;
        this.blockOffsets = new HashMap<>();
        this.blockEndOffsets = new HashMap<>();
        this.pendingJumps = new ArrayList<>();
        this.stackResidentValues = new HashSet<>();
        this.blockHeadPreload = new HashMap<>();
        this.preloadedOnStack = new HashSet<>();
        this.inlinedConstants = new HashSet<>();
        this.inlinedConstantValue = new HashMap<>();
        this.handlerExceptionCaptures = new HashSet<>();
        this.newToInit = new HashMap<>();
        this.initToNew = new HashMap<>();
    }

    public IRMethod getMethod() {
        return method;
    }

    public ConstPool getConstPool() {
        return constPool;
    }

    public RegisterAllocator getRegAlloc() {
        return regAlloc;
    }

    public StackScheduler getScheduler() {
        return scheduler;
    }

    public ByteArrayOutputStream getBytecode() {
        return bytecode;
    }

    public DataOutputStream getDos() {
        return dos;
    }

    public Map<IRBlock, Integer> getBlockOffsets() {
        return blockOffsets;
    }

    public Map<IRBlock, Integer> getBlockEndOffsets() {
        return blockEndOffsets;
    }

    public int getCurrentOffset() {
        return currentOffset;
    }

    public Set<SSAValue> getStackResidentValues() {
        return stackResidentValues;
    }

    public Set<SSAValue> getInlinedConstants() {
        return inlinedConstants;
    }

    public Map<SSAValue, Constant> getInlinedConstantValue() {
        return inlinedConstantValue;
    }

    public Set<SSAValue> getHandlerExceptionCaptures() {
        return handlerExceptionCaptures;
    }

    public Map<NewInstruction, InvokeInstruction> getNewToInit() {
        return newToInit;
    }

    public Map<InvokeInstruction, NewInstruction> getInitToNew() {
        return initToNew;
    }

    public IRBlock getNextBlock() {
        return nextBlock;
    }

    /**
     * Emits bytecode for the IR method.
     *
     * @return the generated bytecode
     */
    public byte[] emit() {
        bytecode = new ByteArrayOutputStream();
        dos = new DataOutputStream(bytecode);
        currentOffset = 0;

        analyzeInlinedConstants();
        analyzeStackResidentValues();
        analyzeConstructorPairs();
        identifyHandlerExceptionCaptures();

        try {
            List<IRBlock> orderedBlocks = computeOptimalBlockOrder();
            for (int i = 0; i < orderedBlocks.size(); i++) {
                IRBlock block = orderedBlocks.get(i);
                // Track what block comes next for fall-through optimization
                nextBlock = (i + 1 < orderedBlocks.size()) ? orderedBlocks.get(i + 1) : null;
                emitBlock(block);
            }
            fixupJumps();
        } catch (IOException e) {
            throw new RuntimeException("Failed to emit bytecode", e);
        }

        return bytecode.toByteArray();
    }

    /**
     * Computes an optimal block ordering that maximizes fall-through opportunities.
     * Uses a greedy algorithm that places fall-through successors immediately after their predecessors.
     */
    private List<IRBlock> computeOptimalBlockOrder() {
        List<IRBlock> order = new ArrayList<>();
        Set<IRBlock> placed = new HashSet<>();
        Deque<IRBlock> worklist = new ArrayDeque<>();

        IRBlock entry = method.getEntryBlock();
        if (entry == null) {
            return method.getBlocksInOrder(); // Fallback to original order
        }

        worklist.add(entry);

        while (!worklist.isEmpty()) {
            IRBlock block = worklist.pollFirst();
            if (placed.contains(block)) continue;

            placed.add(block);
            order.add(block);

            IRBlock fallThrough = getFallThroughSuccessor(block);

            // Add fall-through first (will be processed next)
            if (fallThrough != null && !placed.contains(fallThrough)) {
                worklist.addFirst(fallThrough);
            }

            for (IRBlock succ : block.getSuccessors()) {
                if (!placed.contains(succ)) {
                    worklist.addLast(succ);
                }
            }
        }

        // Add any remaining blocks (shouldn't happen with well-formed CFG)
        for (IRBlock block : method.getBlocks()) {
            if (!placed.contains(block)) {
                order.add(block);
            }
        }

        return order;
    }

    /**
     * Determines the preferred fall-through successor for a block.
     * For branches, prefers the false target as fall-through.
     * For gotos, the only successor is the fall-through candidate.
     */
    private IRBlock getFallThroughSuccessor(IRBlock block) {
        IRInstruction term = block.getTerminator();
        if (term instanceof BranchInstruction) {
            BranchInstruction branch = (BranchInstruction) term;
            return branch.getFalseTarget();
        }
        if (term instanceof SimpleInstruction) {
            SimpleInstruction simple = (SimpleInstruction) term;
            if (simple.getOp() == SimpleOp.GOTO) {
                return simple.getTarget();
            }
        }
        return null;
    }

    /**
     * Identifies single-use literal constants that can be emitted inline at their use site
     * (e.g. {@code iconst_1}) rather than materialized into a local slot and reloaded. This
     * mirrors how javac emits constants and avoids spurious local variables on the round-trip.
     *
     * <p>A constant is inlinable only when it is used exactly once and that use routes its
     * operands through {@link #emitOperandLoads} (i.e. not a copy/goto), so the constant can
     * be pushed at the exact point the consumer reads it, in operand order.
     */
    private void analyzeInlinedConstants() {
        inlinedConstants.clear();
        inlinedConstantValue.clear();

        Map<SSAValue, Constant> literalResults = new HashMap<>();
        for (IRBlock block : method.getBlocksInOrder()) {
            for (IRInstruction instr : block.getInstructions()) {
                if (instr instanceof ConstantInstruction) {
                    ConstantInstruction ci = (ConstantInstruction) instr;
                    SSAValue result = ci.getResult();
                    if (result != null && isInlinableConstant(ci.getConstant())) {
                        literalResults.put(result, ci.getConstant());
                    }
                }
            }
        }

        Map<SSAValue, Integer> useCounts = new HashMap<>();
        Map<SSAValue, IRInstruction> singleUser = new HashMap<>();
        for (IRBlock block : method.getBlocksInOrder()) {
            for (IRInstruction instr : block.getInstructions()) {
                for (Value operand : instr.getOperands()) {
                    if (operand instanceof SSAValue && literalResults.containsKey(operand)) {
                        SSAValue ssa = (SSAValue) operand;
                        useCounts.merge(ssa, 1, Integer::sum);
                        singleUser.put(ssa, instr);
                    }
                }
            }
        }

        for (Map.Entry<SSAValue, Constant> entry : literalResults.entrySet()) {
            SSAValue result = entry.getKey();
            if (useCounts.getOrDefault(result, 0) != 1) continue;
            if (!routesOperandsThroughLoads(singleUser.get(result))) continue;
            inlinedConstants.add(result);
            inlinedConstantValue.put(result, entry.getValue());
        }
    }

    /**
     * Constants {@link #emitConstantValue} knows how to push. Method-handle/type and dynamic
     * constants are excluded since they have no inline push form here.
     */
    private boolean isInlinableConstant(Constant constant) {
        return constant instanceof IntConstant
            || constant instanceof LongConstant
            || constant instanceof FloatConstant
            || constant instanceof DoubleConstant
            || constant instanceof StringConstant
            || constant instanceof NullConstant
            || constant instanceof ClassConstant;
    }

    /**
     * True when an instruction's SSA operands are pushed via {@link #emitOperandLoads}. Copies
     * (from phi elimination) and gotos read their source directly, so a constant consumed by
     * them cannot be inlined.
     */
    private boolean routesOperandsThroughLoads(IRInstruction instr) {
        if (instr == null) return false;
        if (instr instanceof ConstantInstruction
            || instr instanceof CopyInstruction
            || instr instanceof PhiInstruction) {
            return false;
        }
        return !(instr instanceof SimpleInstruction)
                || ((SimpleInstruction) instr).getOp() != SimpleOp.GOTO;
    }

    /**
     * Records each handler block's leading self-copy marker value — the caught exception the JVM places on
     * the entry stack. These must be stored off the stack at handler entry (see {@link #emitCopy}).
     */
    private void identifyHandlerExceptionCaptures() {
        handlerExceptionCaptures.clear();
        for (ExceptionHandler handler : method.getExceptionHandlers()) {
            IRBlock handlerBlock = handler.getHandlerBlock();
            if (handlerBlock == null || handlerBlock.getInstructions().isEmpty()) {
                continue;
            }
            IRInstruction first = handlerBlock.getInstructions().get(0);
            if (first instanceof CopyInstruction) {
                CopyInstruction copy = (CopyInstruction) first;
                if (copy.getResult() != null && copy.getSource() == copy.getResult()) {
                    handlerExceptionCaptures.add(copy.getResult());
                }
            }
        }
    }

    /**
     * Identifies values that can remain on the stack instead of being stored to a register.
     */
    private void analyzeStackResidentValues() {
        stackResidentValues.clear();
        blockHeadPreload.clear();
        preloadedOnStack.clear();

        Map<SSAValue, Integer> useCounts = new HashMap<>();
        for (IRBlock block : method.getBlocksInOrder()) {
            for (IRInstruction instr : block.getInstructions()) {
                for (Value operand : instr.getOperands()) {
                    if (operand instanceof SSAValue) {
                        SSAValue ssa = (SSAValue) operand;
                        useCounts.merge(ssa, 1, Integer::sum);
                    }
                }
            }
        }

        for (IRBlock block : method.getBlocksInOrder()) {
            List<IRInstruction> instructions = block.getInstructions();
            Map<IRInstruction, Integer> indexOf = new HashMap<>();
            Map<SSAValue, Integer> defIdxOf = new HashMap<>();
            for (int k = 0; k < instructions.size(); k++) {
                indexOf.put(instructions.get(k), k);
                SSAValue r = instructions.get(k).getResult();
                if (r != null) {
                    defIdxOf.put(r, k);
                }
            }

            for (int i = 0; i < instructions.size() - 1; i++) {
                IRInstruction current = instructions.get(i);

                if (!current.hasResult()) continue;
                SSAValue result = current.getResult();
                if (result == null) continue;
                if (inlinedConstants.contains(result)) continue;

                int useCount = useCounts.getOrDefault(result, 0);
                if (useCount != 1) continue;

                IRInstruction next = nextEmittedInstruction(instructions, i);
                if (next == null) continue;

                List<Value> nextOperands = next.getOperands();
                if (nextOperands.isEmpty()) continue;

                int p = nextOperands.indexOf(result);
                if (p >= 0 && prefixResidentInOrder(nextOperands, p, defIdxOf, i)
                        && suffixSimple(nextOperands, p)) {
                    stackResidentValues.add(result);
                } else if (isReceiverStackResident(instructions, defIdxOf, useCounts, i, result)) {
                    stackResidentValues.add(result);
                }
            }
        }

        computeBlockHeadPreloads(useCounts);
    }

    /**
     * For a condition block ending in a two-operand comparison branch {@code if reg <cmp> bound} where the
     * bound is a closed sub-computation filling the rest of the block and the first operand is loaded from a
     * register (e.g. a loop induction variable), the register operand is pushed at the block head so the bound
     * stays on the operand stack - matching javac's {@code iload i; <bound>; if_icmplt} rather than spilling
     * the bound to a header local. That spill is what forces the decompiler into a {@code while(true)}+break
     * loop (and reuses the bound's slot) on round trip. Safe because the emitter never emits a {@code dup_x}
     * or {@code swap}, so the preloaded register stays at the bottom while the bound's closed sub-tree is
     * computed above it.
     */
    private void computeBlockHeadPreloads(Map<SSAValue, Integer> useCounts) {
        for (IRBlock block : method.getBlocksInOrder()) {
            List<IRInstruction> instrs = block.getInstructions();
            if (instrs.size() < 2) {
                continue;
            }
            IRInstruction term = instrs.get(instrs.size() - 1);
            if (!(term instanceof BranchInstruction)) {
                continue;
            }
            List<Value> ops = term.getOperands();
            if (ops.size() != 2 || !(ops.get(0) instanceof SSAValue) || !(ops.get(1) instanceof SSAValue)) {
                continue;
            }
            SSAValue reg = (SSAValue) ops.get(0);
            SSAValue bound = (SSAValue) ops.get(1);
            if (useCounts.getOrDefault(bound, 0) != 1) {
                continue; // the bound must be consumed only by this branch
            }

            Set<SSAValue> blockResults = new HashSet<>();
            for (IRInstruction in : instrs) {
                if (in.getResult() != null) {
                    blockResults.add(in.getResult());
                }
            }
            if (blockResults.contains(reg) || !blockResults.contains(bound)) {
                continue; // reg must be a plain register load; bound must be computed in this block
            }

            // Transitive closure of the bound over its operands, within this block.
            Set<SSAValue> closure = new HashSet<>();
            List<SSAValue> work = new ArrayList<>();
            work.add(bound);
            while (!work.isEmpty()) {
                SSAValue v = work.remove(work.size() - 1);
                if (!closure.add(v)) {
                    continue;
                }
                for (int k = 0; k < instrs.size() - 1; k++) {
                    if (v.equals(instrs.get(k).getResult())) {
                        for (Value o : instrs.get(k).getOperands()) {
                            if (o instanceof SSAValue) {
                                work.add((SSAValue) o);
                            }
                        }
                    }
                }
            }

            // Every non-terminator instruction must feed the bound and stay on the stack (be resident), and
            // none may consume reg early, so emitting the block leaves exactly the bound above the preloaded reg.
            boolean clean = true;
            for (int k = 0; k < instrs.size() - 1; k++) {
                IRInstruction in = instrs.get(k);
                SSAValue r = in.getResult();
                // Each non-terminator must feed the bound and either stay on the stack (be the bound or a
                // resident value) or emit nothing at its position (an inlined constant, pushed at its use);
                // and none may consume the preloaded register early.
                if (r == null || !closure.contains(r)
                        || !(r.equals(bound) || stackResidentValues.contains(r) || inlinedConstants.contains(r))
                        || in.getOperands().contains(reg)) {
                    clean = false;
                    break;
                }
            }
            if (!clean) {
                continue;
            }

            stackResidentValues.add(bound);
            blockHeadPreload.put(block, reg);
        }
    }

    /**
     * Whether operands 0..p-1 of an instruction are all stack-resident and defined in strictly increasing order
     * ending just before {@code resultDefIdx} - so this value (operand p, computed last) sits on top of them in
     * the exact operand order the instruction needs. This lets a call argument stay on the stack once its
     * receiver (and earlier arguments) are already resident, instead of being spilled to a local and reloaded.
     */
    private boolean prefixResidentInOrder(List<Value> ops, int p, Map<SSAValue, Integer> defIdxOf,
                                          int resultDefIdx) {
        int prev = -1;
        for (int q = 0; q < p; q++) {
            Value o = ops.get(q);
            if (!(o instanceof SSAValue) || !stackResidentValues.contains((SSAValue) o)) {
                return false;
            }
            Integer di = defIdxOf.get((SSAValue) o);
            if (di == null || di <= prev || di >= resultDefIdx) {
                return false;
            }
            prev = di;
        }
        return true;
    }

    /** Whether operands after position p are all simple - loaded fresh at the use, on top of operand p. */
    private boolean suffixSimple(List<Value> ops, int p) {
        for (int q = p + 1; q < ops.size(); q++) {
            if (!isSimpleOperand(ops.get(q))) {
                return false;
            }
        }
        return true;
    }

    /**
     * Whether a single-use value that is the FIRST operand (the receiver) of a later instruction can stay on
     * the operand stack across the instructions that compute that instruction's remaining operands - matching
     * how javac keeps a call receiver below its arguments, instead of spilling it to a (type-reused) local.
     *
     * <p>Safe because (a) the emitter never emits {@code dup_x*}/{@code swap}, so nothing computed on top of
     * the receiver can reach below it, and (b) the window between the receiver's definition and its use is
     * "closed" - every value it produces is consumed inside the window or by the use - so it computes exactly
     * the use's later operands and leaves the receiver undisturbed at the bottom. The later operands must all
     * be produced within the window, in operand order, so the use sees {@code [receiver, op1, op2, ...]}.
     */
    private boolean isReceiverStackResident(List<IRInstruction> instructions, Map<SSAValue, Integer> defIdxOf,
                                            Map<SSAValue, Integer> useCounts, int defIdx, SSAValue result) {
        // The single use, found by scanning operands (the emitter's reliable use source - getUses() can be stale).
        IRInstruction use = null;
        int useIdx = -1;
        for (int j = defIdx + 1; j < instructions.size(); j++) {
            if (instructions.get(j).getOperands().contains(result)) {
                use = instructions.get(j);
                useIdx = j;
                break;
            }
        }
        if (use == null || (use instanceof InvokeInstruction && initToNew.containsKey((InvokeInstruction) use))) {
            return false; // use not in this block, or a new/<init> pairing we must not disturb
        }
        if (useIdx <= defIdx + 1) {
            return false; // empty window - the adjacent case is handled above
        }
        List<Value> ops = use.getOperands();
        if (ops.isEmpty() || !result.equals(ops.get(0))) {
            return false; // result must be the receiver (first operand)
        }

        int wStart = defIdx + 1, wEnd = useIdx;
        // Every later operand must be produced inside the window, strictly in operand order, so the use sees
        // [receiver, op1, op2, ...] with nothing loaded out of order on top.
        int prevDefIdx = defIdx;
        for (int k = 1; k < ops.size(); k++) {
            if (!(ops.get(k) instanceof SSAValue)) {
                return false;
            }
            Integer opDefIdx = defIdxOf.get((SSAValue) ops.get(k));
            if (opDefIdx == null || opDefIdx < wStart || opDefIdx >= wEnd || opDefIdx <= prevDefIdx) {
                return false;
            }
            prevDefIdx = opDefIdx;
        }
        // Window closed: every value the window produces is consumed inside the window or by the use - so it
        // computes exactly the use's later operands and leaves the receiver undisturbed below them.
        for (int j = wStart; j < wEnd; j++) {
            SSAValue r = instructions.get(j).getResult();
            if (r == null) {
                continue;
            }
            int within = 0;
            for (int q = wStart; q <= wEnd; q++) {
                for (Value op : instructions.get(q).getOperands()) {
                    if (r.equals(op)) within++;
                }
            }
            if (within != useCounts.getOrDefault(r, 0)) {
                return false; // some use escapes the window
            }
        }
        return true;
    }

    /**
     * The next instruction after {@code afterIndex} that actually emits code. Inlined-constant
     * definitions emit nothing (they are pushed at their use site), so they must be skipped when
     * testing whether a value's consumer is adjacent — otherwise a single-use binop result feeding
     * a comparison like {@code i * i <= n} or {@code n % i == 0} would be needlessly spilled to a
     * slot just because the comparison's constant operand sits between them.
     */
    private IRInstruction nextEmittedInstruction(List<IRInstruction> instructions, int afterIndex) {
        for (int j = afterIndex + 1; j < instructions.size(); j++) {
            IRInstruction candidate = instructions.get(j);
            if (candidate instanceof ConstantInstruction
                    && inlinedConstants.contains(candidate.getResult())) {
                continue;
            }
            return candidate;
        }
        return null;
    }

    /**
     * Whether an operand can be pushed after a stack-resident first operand without disturbing it.
     * The second operand is emitted after the first is already on the stack, so it must be a single
     * fresh push that leaves the first untouched: a constant, or any value loaded from a
     * register/parameter. The only unsafe case is an operand that is itself stack-resident — and a
     * second operand never is, since stack-residency keys on being the <em>first</em> operand of the
     * immediately-following instruction (params/locals reach here with a dangling load definition,
     * so a definition-based test is unreliable; stack-residency membership is the correct one).
     */
    private boolean isSimpleOperand(Value operand) {
        if (operand instanceof Constant) return true;
        if (operand instanceof SSAValue) {
            return !stackResidentValues.contains((SSAValue) operand);
        }
        return false;
    }

    private void emitBlock(IRBlock block) throws IOException {
        blockOffsets.put(block, currentOffset);

        SSAValue preload = blockHeadPreload.get(block);
        if (preload != null) {
            emitLoadValue(preload);
            preloadedOnStack.add(preload);
        }

        for (IRInstruction instr : block.getInstructions()) {
            emitInstruction(instr);
        }

        blockEndOffsets.put(block, currentOffset);
    }

    private void emitInstruction(IRInstruction instr) throws IOException {
        if (instr instanceof ConstantInstruction && inlinedConstants.contains(instr.getResult())) {
            return;
        }

        if (instr instanceof NewInstruction && newToInit.containsKey(instr)) {
            emitNew((NewInstruction) instr);
            emit(Opcode.DUP.getCode());
            return;
        }
        if (instr instanceof InvokeInstruction && initToNew.containsKey(instr)) {
            emitPairedInit((InvokeInstruction) instr);
            return;
        }

        emitOperandLoads(instr);

        if (instr instanceof ConstantInstruction) {
            ConstantInstruction constInstr = (ConstantInstruction) instr;
            emitConstant(constInstr);
        } else if (instr instanceof LoadLocalInstruction) {
            LoadLocalInstruction load = (LoadLocalInstruction) instr;
            emitLoad(load);
        } else if (instr instanceof BinaryOpInstruction) {
            BinaryOpInstruction binOp = (BinaryOpInstruction) instr;
            emitBinaryOp(binOp);
        } else if (instr instanceof UnaryOpInstruction) {
            UnaryOpInstruction unaryOp = (UnaryOpInstruction) instr;
            emitUnaryOp(unaryOp);
        } else if (instr instanceof SimpleInstruction) {
            SimpleInstruction simple = (SimpleInstruction) instr;
            emitSimple(simple);
        } else if (instr instanceof BranchInstruction) {
            BranchInstruction branch = (BranchInstruction) instr;
            emitBranch(branch);
        } else if (instr instanceof ReturnInstruction) {
            ReturnInstruction ret = (ReturnInstruction) instr;
            emitReturn(ret);
        } else if (instr instanceof InvokeInstruction) {
            InvokeInstruction invoke = (InvokeInstruction) instr;
            emitInvoke(invoke);
        } else if (instr instanceof FieldAccessInstruction) {
            FieldAccessInstruction fieldAccess = (FieldAccessInstruction) instr;
            emitFieldAccess(fieldAccess);
        } else if (instr instanceof NewInstruction) {
            NewInstruction newInstr = (NewInstruction) instr;
            emitNew(newInstr);
        } else if (instr instanceof NewArrayInstruction) {
            NewArrayInstruction newArray = (NewArrayInstruction) instr;
            emitNewArray(newArray);
        } else if (instr instanceof ArrayAccessInstruction) {
            ArrayAccessInstruction arrayAccess = (ArrayAccessInstruction) instr;
            emitArrayAccess(arrayAccess);
        } else if (instr instanceof TypeCheckInstruction) {
            TypeCheckInstruction typeCheck = (TypeCheckInstruction) instr;
            emitTypeCheck(typeCheck);
        } else if (instr instanceof SwitchInstruction) {
            SwitchInstruction switchInstr = (SwitchInstruction) instr;
            emitSwitch(switchInstr);
        } else if (instr instanceof CopyInstruction) {
            CopyInstruction copy = (CopyInstruction) instr;
            emitCopy(copy);
        }

        emitResultStore(instr);
    }

    /** Pairs each {@code new} with the same-block {@code <init>} whose receiver is the new's result. */
    private void analyzeConstructorPairs() {
        newToInit.clear();
        initToNew.clear();
        for (IRBlock block : method.getBlocksInOrder()) {
            List<IRInstruction> instructions = block.getInstructions();
            for (int i = 0; i < instructions.size(); i++) {
                if (!(instructions.get(i) instanceof NewInstruction)) {
                    continue;
                }
                NewInstruction newInstr = (NewInstruction) instructions.get(i);
                SSAValue result = newInstr.getResult();
                if (result == null) {
                    continue;
                }
                for (int j = i + 1; j < instructions.size(); j++) {
                    if (!(instructions.get(j) instanceof InvokeInstruction)) {
                        continue;
                    }
                    InvokeInstruction invoke = (InvokeInstruction) instructions.get(j);
                    List<Value> ops = invoke.getOperands();
                    if (invoke.getInvokeType() == InvokeType.SPECIAL && "<init>".equals(invoke.getName())
                            && !ops.isEmpty() && result.equals(ops.get(0))) {
                        newToInit.put(newInstr, invoke);
                        initToNew.put(invoke, newInstr);
                        // A paired construction stores its result to a local after invokespecial; it must never be
                        // left stack-resident, or the constructed object lingers on the stack across later branches
                        // and joins reach inconsistent stack depths (unverifiable). Consumers load it from the local.
                        stackResidentValues.remove(result);
                        break;
                    }
                }
            }
        }
    }

    /**
     * Emits a paired constructor {@code <init>}: the receiver is already on the stack (from {@code new; dup}), so only
     * the constructor arguments are loaded; after {@code invokespecial} the initialized reference is stored as the
     * paired {@code new}'s result.
     */
    private void emitPairedInit(InvokeInstruction instr) throws IOException {
        List<Value> operands = instr.getOperands();
        for (int i = 1; i < operands.size(); i++) {
            Value operand = operands.get(i);
            if (operand instanceof SSAValue) {
                SSAValue ssa = (SSAValue) operand;
                if (inlinedConstants.contains(ssa)) {
                    emitConstantValue(inlinedConstantValue.get(ssa));
                } else if (!stackResidentValues.contains(ssa)) {
                    emitLoadValue(ssa);
                }
            } else if (operand instanceof Constant) {
                emitConstantValue((Constant) operand);
            }
        }
        emitInvoke(instr);

        SSAValue result = initToNew.get(instr).getResult();
        if (result != null && !stackResidentValues.contains(result)) {
            emitVarInsn(Opcode.ASTORE.getCode(), Opcode.ASTORE_0.getCode(), regAlloc.getRegister(result));
        }
    }

    private void emitOperandLoads(IRInstruction instr) throws IOException {
        if (instr instanceof ConstantInstruction ||
            instr instanceof LoadLocalInstruction ||
            instr instanceof StoreLocalInstruction ||
            instr instanceof CopyInstruction) {
            return;
        }
        if (instr instanceof SimpleInstruction) {
            SimpleInstruction simple = (SimpleInstruction) instr;
            if (simple.getOp() == SimpleOp.GOTO) {
                return;
            }
        }

        for (Value operand : instr.getOperands()) {
            if (operand instanceof SSAValue) {
                SSAValue ssa = (SSAValue) operand;
                if (preloadedOnStack.remove(ssa)) {
                    continue; // pushed at the block head, already on the stack
                }
                if (inlinedConstants.contains(ssa)) {
                    emitConstantValue(inlinedConstantValue.get(ssa));
                    continue;
                }
                if (stackResidentValues.contains(ssa)) {
                    continue;
                }
                emitLoadValue(ssa);
            } else if (operand instanceof Constant) {
                emitConstantValue((Constant) operand);
            }
        }
    }

    private void emitLoadValue(SSAValue value) throws IOException {
        int reg = regAlloc.getRegister(value);
        if (reg < 0) {
            throw new IllegalStateException("No register allocated for value: " + value + " (name=" + value.getName() + ")");
        }
        IRType type = value.getType();

        if (type instanceof PrimitiveType) {
            PrimitiveType prim = (PrimitiveType) type;
            switch (prim) {
                case INT:
                case BOOLEAN:
                case BYTE:
                case CHAR:
                case SHORT:
                    emitVarInsn(Opcode.ILOAD.getCode(), Opcode.ILOAD_0.getCode(), reg);
                    break;
                case LONG:
                    emitVarInsn(Opcode.LLOAD.getCode(), Opcode.LLOAD_0.getCode(), reg);
                    break;
                case FLOAT:
                    emitVarInsn(Opcode.FLOAD.getCode(), Opcode.FLOAD_0.getCode(), reg);
                    break;
                case DOUBLE:
                    emitVarInsn(Opcode.DLOAD.getCode(), Opcode.DLOAD_0.getCode(), reg);
                    break;
            }
        } else {
            emitVarInsn(Opcode.ALOAD.getCode(), Opcode.ALOAD_0.getCode(), reg);
        }
    }

    private void emitConstantValue(Constant constant) throws IOException {
        if (constant instanceof IntConstant) {
            IntConstant intConst = (IntConstant) constant;
            int value = intConst.getValue();
            if (value >= -1 && value <= 5) {
                emit(Opcode.ICONST_0.getCode() + value);
            } else if (value >= Byte.MIN_VALUE && value <= Byte.MAX_VALUE) {
                emit(Opcode.BIPUSH.getCode());
                emit((byte) value);
            } else if (value >= Short.MIN_VALUE && value <= Short.MAX_VALUE) {
                emit(Opcode.SIPUSH.getCode());
                emitShort((short) value);
            } else {
                int index = constPool.findOrAddInteger(value).getIndex(constPool);
                emitLdc(index);
            }
        } else if (constant instanceof LongConstant) {
            LongConstant longConst = (LongConstant) constant;
            long value = longConst.getValue();
            if (value == 0L) emit(Opcode.LCONST_0.getCode());
            else if (value == 1L) emit(Opcode.LCONST_1.getCode());
            else {
                int index = constPool.findOrAddLong(value).getIndex(constPool);
                emit(Opcode.LDC2_W.getCode());
                emitShort((short) index);
            }
        } else if (constant instanceof FloatConstant) {
            FloatConstant floatConst = (FloatConstant) constant;
            float value = floatConst.getValue();
            if (value == 0.0f) emit(Opcode.FCONST_0.getCode());
            else if (value == 1.0f) emit(Opcode.FCONST_1.getCode());
            else if (value == 2.0f) emit(Opcode.FCONST_2.getCode());
            else {
                int index = constPool.findOrAddFloat(value).getIndex(constPool);
                emitLdc(index);
            }
        } else if (constant instanceof DoubleConstant) {
            DoubleConstant doubleConst = (DoubleConstant) constant;
            double value = doubleConst.getValue();
            if (value == 0.0) emit(Opcode.DCONST_0.getCode());
            else if (value == 1.0) emit(Opcode.DCONST_1.getCode());
            else {
                int index = constPool.findOrAddDouble(value).getIndex(constPool);
                emit(Opcode.LDC2_W.getCode());
                emitShort((short) index);
            }
        } else if (constant instanceof StringConstant) {
            StringConstant stringConst = (StringConstant) constant;
            int index = constPool.findOrAddString(stringConst.getValue()).getIndex(constPool);
            emitLdc(index);
        } else if (constant instanceof NullConstant) {
            emit(Opcode.ACONST_NULL.getCode());
        } else if (constant instanceof ClassConstant) {
            ClassConstant classConst = (ClassConstant) constant;
            int index = constPool.findOrAddClass(classConst.getClassName()).getIndex(constPool);
            emitLdc(index);
        }
    }

    private void emitResultStore(IRInstruction instr) throws IOException {
        if (!instr.hasResult()) return;
        SSAValue result = instr.getResult();
        if (result == null) return;

        if (instr instanceof CopyInstruction ||
            instr instanceof LoadLocalInstruction ||
            instr instanceof StoreLocalInstruction) {
            return;
        }

        if (stackResidentValues.contains(result)) {
            return;
        }

        int reg = regAlloc.getRegister(result);
        IRType type = result.getType();

        if (type instanceof PrimitiveType) {
            PrimitiveType prim = (PrimitiveType) type;
            switch (prim) {
                case INT:
                case BOOLEAN:
                case BYTE:
                case CHAR:
                case SHORT:
                    emitVarInsn(Opcode.ISTORE.getCode(), Opcode.ISTORE_0.getCode(), reg);
                    break;
                case LONG:
                    emitVarInsn(Opcode.LSTORE.getCode(), Opcode.LSTORE_0.getCode(), reg);
                    break;
                case FLOAT:
                    emitVarInsn(Opcode.FSTORE.getCode(), Opcode.FSTORE_0.getCode(), reg);
                    break;
                case DOUBLE:
                    emitVarInsn(Opcode.DSTORE.getCode(), Opcode.DSTORE_0.getCode(), reg);
                    break;
            }
        } else {
            emitVarInsn(Opcode.ASTORE.getCode(), Opcode.ASTORE_0.getCode(), reg);
        }
    }

    private void emitConstant(ConstantInstruction instr) throws IOException {
        Constant constant = instr.getConstant();

        if (constant instanceof IntConstant) {
            IntConstant intConst = (IntConstant) constant;
            int value = intConst.getValue();
            if (value >= -1 && value <= 5) {
                emit(Opcode.ICONST_0.getCode() + value);
            } else if (value >= Byte.MIN_VALUE && value <= Byte.MAX_VALUE) {
                emit(Opcode.BIPUSH.getCode());
                emit((byte) value);
            } else if (value >= Short.MIN_VALUE && value <= Short.MAX_VALUE) {
                emit(Opcode.SIPUSH.getCode());
                emitShort((short) value);
            } else {
                int index = constPool.findOrAddInteger(value).getIndex(constPool);
                emitLdc(index);
            }
        } else if (constant instanceof LongConstant) {
            LongConstant longConst = (LongConstant) constant;
            long value = longConst.getValue();
            if (value == 0L) {
                emit(Opcode.LCONST_0.getCode());
            } else if (value == 1L) {
                emit(Opcode.LCONST_1.getCode());
            } else {
                int index = constPool.findOrAddLong(value).getIndex(constPool);
                emit(Opcode.LDC2_W.getCode());
                emitShort((short) index);
            }
        } else if (constant instanceof FloatConstant) {
            FloatConstant floatConst = (FloatConstant) constant;
            float value = floatConst.getValue();
            if (value == 0.0f) {
                emit(Opcode.FCONST_0.getCode());
            } else if (value == 1.0f) {
                emit(Opcode.FCONST_1.getCode());
            } else if (value == 2.0f) {
                emit(Opcode.FCONST_2.getCode());
            } else {
                int index = constPool.findOrAddFloat(value).getIndex(constPool);
                emitLdc(index);
            }
        } else if (constant instanceof DoubleConstant) {
            DoubleConstant doubleConst = (DoubleConstant) constant;
            double value = doubleConst.getValue();
            if (value == 0.0) {
                emit(Opcode.DCONST_0.getCode());
            } else if (value == 1.0) {
                emit(Opcode.DCONST_1.getCode());
            } else {
                int index = constPool.findOrAddDouble(value).getIndex(constPool);
                emit(Opcode.LDC2_W.getCode());
                emitShort((short) index);
            }
        } else if (constant instanceof StringConstant) {
            StringConstant stringConst = (StringConstant) constant;
            int index = constPool.findOrAddString(stringConst.getValue()).getIndex(constPool);
            emitLdc(index);
        } else if (constant instanceof NullConstant) {
            emit(Opcode.ACONST_NULL.getCode());
        } else if (constant instanceof ClassConstant) {
            ClassConstant classConst = (ClassConstant) constant;
            int index = constPool.findOrAddClass(classConst.getClassName()).getIndex(constPool);
            emitLdc(index);
        } else if (constant instanceof MethodHandleConstant) {
            MethodHandleConstant mhConst = (MethodHandleConstant) constant;
            int index = constPool.findOrAddMethodHandle(
                    mhConst.getReferenceKind(),
                    mhConst.getOwner(),
                    mhConst.getName(),
                    mhConst.getDescriptor()
            ).getIndex(constPool);
            emitLdc(index);
        } else if (constant instanceof MethodTypeConstant) {
            MethodTypeConstant mtConst = (MethodTypeConstant) constant;
            int index = constPool.findOrAddMethodType(mtConst.getDescriptor()).getIndex(constPool);
            emitLdc(index);
        } else if (constant instanceof DynamicConstant) {
            DynamicConstant dynConst = (DynamicConstant) constant;
            int migratedBsmIndex = migrateBootstrapMethod(dynConst);
            int cpIndex = constPool.findOrAddConstantDynamic(
                    migratedBsmIndex,
                    dynConst.getName(),
                    dynConst.getDescriptor()
            ).getIndex(constPool);
            if (dynConst.getType().isTwoSlot()) {
                emit(Opcode.LDC2_W.getCode());
                emitShort((short) cpIndex);
            } else {
                emitLdc(cpIndex);
            }
        }
    }

    private void emitLdc(int index) throws IOException {
        if (index <= 0) {
            throw new IllegalStateException("Invalid LDC constant pool index: " + index +
                " (must be > 0). This indicates a constant pool lookup failure.");
        }
        if (index <= 255) {
            emit(Opcode.LDC.getCode());
            emit((byte) index);
        } else {
            emit(Opcode.LDC_W.getCode());
            emitShort((short) index);
        }
    }

    private void emitLoad(LoadLocalInstruction instr) throws IOException {
        // Use the RegisterAllocator's slot for the result value, not the original local index.
        // The original local index may be stale after transformations like method inlining.
        SSAValue result = instr.getResult();
        int index = regAlloc.getRegister(result);
        if (index < 0) {
            // No register allocation for this result - it was likely replaced by replaceAllUsesWith
            // during inlining. Skip emitting this instruction entirely.
            // The value has been replaced with another SSAValue that will be loaded when needed.
            return;
        }
        IRType type = result.getType();

        if (type instanceof PrimitiveType) {
            PrimitiveType prim = (PrimitiveType) type;
            switch (prim) {
                case INT:
                case BOOLEAN:
                case BYTE:
                case CHAR:
                case SHORT:
                    emitVarInsn(Opcode.ILOAD.getCode(), Opcode.ILOAD_0.getCode(), index);
                    break;
                case LONG:
                    emitVarInsn(Opcode.LLOAD.getCode(), Opcode.LLOAD_0.getCode(), index);
                    break;
                case FLOAT:
                    emitVarInsn(Opcode.FLOAD.getCode(), Opcode.FLOAD_0.getCode(), index);
                    break;
                case DOUBLE:
                    emitVarInsn(Opcode.DLOAD.getCode(), Opcode.DLOAD_0.getCode(), index);
                    break;
            }
        } else {
            emitVarInsn(Opcode.ALOAD.getCode(), Opcode.ALOAD_0.getCode(), index);
        }
    }

    private void emitVarInsn(int wideOp, int shortOpBase, int index) throws IOException {
        if (index <= 3) {
            emit(shortOpBase + index);
        } else if (index <= 255) {
            emit(wideOp);
            emit((byte) index);
        } else {
            emit(Opcode.WIDE.getCode());
            emit(wideOp);
            emitShort((short) index);
        }
    }

    private void emitBinaryOp(BinaryOpInstruction instr) throws IOException {
        IRType type = instr.getResult().getType();
        int baseOpcode = getBinaryOpcode(instr.getOp(), type);
        emit(baseOpcode);
    }

    private int getBinaryOpcode(BinaryOp op, IRType type) {
        int typeOffset = getTypeOffset(type);
        switch (op) {
            case ADD:
                return Opcode.IADD.getCode() + typeOffset;
            case SUB:
                return Opcode.ISUB.getCode() + typeOffset;
            case MUL:
                return Opcode.IMUL.getCode() + typeOffset;
            case DIV:
                return Opcode.IDIV.getCode() + typeOffset;
            case REM:
                return Opcode.IREM.getCode() + typeOffset;
            case SHL:
                return type == PrimitiveType.LONG ? Opcode.LSHL.getCode() : Opcode.ISHL.getCode();
            case SHR:
                return type == PrimitiveType.LONG ? Opcode.LSHR.getCode() : Opcode.ISHR.getCode();
            case USHR:
                return type == PrimitiveType.LONG ? Opcode.LUSHR.getCode() : Opcode.IUSHR.getCode();
            case AND:
                return type == PrimitiveType.LONG ? Opcode.LAND.getCode() : Opcode.IAND.getCode();
            case OR:
                return type == PrimitiveType.LONG ? Opcode.LOR.getCode() : Opcode.IOR.getCode();
            case XOR:
                return type == PrimitiveType.LONG ? Opcode.LXOR.getCode() : Opcode.IXOR.getCode();
            case LCMP:
                return Opcode.LCMP.getCode();
            case FCMPL:
                return Opcode.FCMPL.getCode();
            case FCMPG:
                return Opcode.FCMPG.getCode();
            case DCMPL:
                return Opcode.DCMPL.getCode();
            case DCMPG:
                return Opcode.DCMPG.getCode();
            default:
                throw new IllegalArgumentException("Unknown binary op: " + op);
        }
    }

    private int getTypeOffset(IRType type) {
        if (type == PrimitiveType.INT) return 0;
        if (type == PrimitiveType.LONG) return 1;
        if (type == PrimitiveType.FLOAT) return 2;
        if (type == PrimitiveType.DOUBLE) return 3;
        return 0;
    }

    private void emitUnaryOp(UnaryOpInstruction instr) throws IOException {
        int opcode;
        switch (instr.getOp()) {
            case NEG: {
                IRType type = instr.getOperand().getType();
                opcode = Opcode.INEG.getCode() + getTypeOffset(type);
                break;
            }
            case I2L:
                opcode = Opcode.I2L.getCode();
                break;
            case I2F:
                opcode = Opcode.I2F.getCode();
                break;
            case I2D:
                opcode = Opcode.I2D.getCode();
                break;
            case L2I:
                opcode = Opcode.L2I.getCode();
                break;
            case L2F:
                opcode = Opcode.L2F.getCode();
                break;
            case L2D:
                opcode = Opcode.L2D.getCode();
                break;
            case F2I:
                opcode = Opcode.F2I.getCode();
                break;
            case F2L:
                opcode = Opcode.F2L.getCode();
                break;
            case F2D:
                opcode = Opcode.F2D.getCode();
                break;
            case D2I:
                opcode = Opcode.D2I.getCode();
                break;
            case D2L:
                opcode = Opcode.D2L.getCode();
                break;
            case D2F:
                opcode = Opcode.D2F.getCode();
                break;
            case I2B:
                opcode = Opcode.I2B.getCode();
                break;
            case I2C:
                opcode = Opcode.I2C.getCode();
                break;
            case I2S:
                opcode = Opcode.I2S.getCode();
                break;
            default:
                throw new IllegalStateException("Unknown unary op: " + instr.getOp());
        }
        emit(opcode);
    }

    private void emitBranch(BranchInstruction instr) throws IOException {
        int opcode;
        switch (instr.getCondition()) {
            case IFEQ:
                opcode = Opcode.IFEQ.getCode();
                break;
            case IFNE:
                opcode = Opcode.IFNE.getCode();
                break;
            case IFLT:
                opcode = Opcode.IFLT.getCode();
                break;
            case IFGE:
                opcode = Opcode.IFGE.getCode();
                break;
            case IFGT:
                opcode = Opcode.IFGT.getCode();
                break;
            case IFLE:
                opcode = Opcode.IFLE.getCode();
                break;
            case EQ:
                opcode = Opcode.IF_ICMPEQ.getCode();
                break;
            case NE:
                opcode = Opcode.IF_ICMPNE.getCode();
                break;
            case LT:
                opcode = Opcode.IF_ICMPLT.getCode();
                break;
            case GE:
                opcode = Opcode.IF_ICMPGE.getCode();
                break;
            case GT:
                opcode = Opcode.IF_ICMPGT.getCode();
                break;
            case LE:
                opcode = Opcode.IF_ICMPLE.getCode();
                break;
            case ACMPEQ:
                opcode = Opcode.IF_ACMPEQ.getCode();
                break;
            case ACMPNE:
                opcode = Opcode.IF_ACMPNE.getCode();
                break;
            case IFNULL:
                opcode = Opcode.IFNULL.getCode();
                break;
            case IFNONNULL:
                opcode = Opcode.IFNONNULL.getCode();
                break;
            default:
                throw new IllegalStateException("Unknown condition: " + instr.getCondition());
        }

        emit(opcode);
        pendingJumps.add(new PendingJump(currentOffset, instr.getTrueTarget(), false));
        emitShort((short) 0);

        // Skip false-branch goto if target is the next block (fall-through optimization)
        if (instr.getFalseTarget() != nextBlock) {
            emit(Opcode.GOTO.getCode());
            pendingJumps.add(new PendingJump(currentOffset, instr.getFalseTarget(), false));
            emitShort((short) 0);
        }
    }

    private void emitReturn(ReturnInstruction instr) throws IOException {
        if (instr.isVoidReturn()) {
            emit(Opcode.RETURN_.getCode());
        } else {
            IRType type = instr.getReturnValue().getType();
            if (type instanceof PrimitiveType) {
                PrimitiveType prim = (PrimitiveType) type;
                int opcode;
                switch (prim) {
                    case INT:
                    case BOOLEAN:
                    case BYTE:
                    case CHAR:
                    case SHORT:
                        opcode = Opcode.IRETURN.getCode();
                        break;
                    case LONG:
                        opcode = Opcode.LRETURN.getCode();
                        break;
                    case FLOAT:
                        opcode = Opcode.FRETURN.getCode();
                        break;
                    case DOUBLE:
                        opcode = Opcode.DRETURN.getCode();
                        break;
                    default:
                        throw new IllegalStateException("Unknown primitive type: " + prim);
                }
                emit(opcode);
            } else {
                emit(Opcode.ARETURN.getCode());
            }
        }
    }

    private void emitInvoke(InvokeInstruction instr) throws IOException {
        int opcode;
        switch (instr.getInvokeType()) {
            case VIRTUAL:
                opcode = Opcode.INVOKEVIRTUAL.getCode();
                break;
            case SPECIAL:
                opcode = Opcode.INVOKESPECIAL.getCode();
                break;
            case STATIC:
                opcode = Opcode.INVOKESTATIC.getCode();
                break;
            case INTERFACE:
                opcode = Opcode.INVOKEINTERFACE.getCode();
                break;
            case DYNAMIC:
                opcode = Opcode.INVOKEDYNAMIC.getCode();
                break;
            default:
                throw new IllegalStateException("Unknown invoke type: " + instr.getInvokeType());
        }

        if (instr.getInvokeType() == InvokeType.DYNAMIC) {
            int cpIndex = instr.getOriginalCpIndex();
            if (cpIndex > 0) {
                emit(opcode);
                emitShort((short) cpIndex);
                emitShort((short) 0);
            } else if (instr.getBootstrapInfo() != null) {
                cpIndex = createInvokeDynamicEntry(instr);
                emit(opcode);
                emitShort((short) cpIndex);
                emitShort((short) 0);
            } else {
                throw new UnsupportedOperationException(
                    "Cannot emit INVOKEDYNAMIC without original constant pool index or bootstrap info. " +
                    "Method: " + instr.getName() + instr.getDescriptor());
            }
            return;
        }

        int cpIndex;
        if (instr.getInvokeType() == InvokeType.INTERFACE) {
            cpIndex = constPool.findOrAddInterfaceRef(
                    instr.getOwner(), instr.getName(), instr.getDescriptor()
            ).getIndex(constPool);
        } else {
            cpIndex = constPool.findOrAddMethodRef(
                    instr.getOwner(), instr.getName(), instr.getDescriptor()
            ).getIndex(constPool);
        }

        emit(opcode);
        emitShort((short) cpIndex);

        if (instr.getInvokeType() == InvokeType.INTERFACE) {
            // invokeinterface count = total argument slots including the receiver (already present
            // in the arguments list), with long/double occupying two slots.
            int count = 0;
            for (Value arg : instr.getArguments()) {
                count += arg.getType() != null && arg.getType().isTwoSlot() ? 2 : 1;
            }
            emit((byte) count);
            emit((byte) 0);
        }
    }

    private void emitNew(NewInstruction instr) throws IOException {
        int classRef = constPool.findOrAddClass(instr.getClassName()).getIndex(constPool);
        emit(Opcode.NEW.getCode());
        emitShort((short) classRef);
    }

    private void emitNewArray(NewArrayInstruction instr) throws IOException {
        IRType elemType = instr.getElementType();

        if (elemType instanceof PrimitiveType) {
            PrimitiveType prim = (PrimitiveType) elemType;
            emit(Opcode.NEWARRAY.getCode());
            int atype;
            switch (prim) {
                case BOOLEAN:
                    atype = AccessFlags.T_BOOLEAN;
                    break;
                case CHAR:
                    atype = AccessFlags.T_CHAR;
                    break;
                case FLOAT:
                    atype = AccessFlags.T_FLOAT;
                    break;
                case DOUBLE:
                    atype = AccessFlags.T_DOUBLE;
                    break;
                case BYTE:
                    atype = AccessFlags.T_BYTE;
                    break;
                case SHORT:
                    atype = AccessFlags.T_SHORT;
                    break;
                case INT:
                    atype = AccessFlags.T_INT;
                    break;
                case LONG:
                    atype = AccessFlags.T_LONG;
                    break;
                default:
                    throw new IllegalStateException("Unknown primitive type: " + prim);
            }
            emit((byte) atype);
        } else if (instr.isMultiDimensional()) {
            String desc = instr.getResult().getType().getDescriptor();
            int classRef = constPool.findOrAddClass(desc).getIndex(constPool);
            emit(Opcode.MULTIANEWARRAY.getCode());
            emitShort((short) classRef);
            emit((byte) instr.getDimensions().size());
        } else {
            String className = elemType.getDescriptor();
            if (className.startsWith("L") && className.endsWith(";")) {
                className = className.substring(1, className.length() - 1);
            }
            int classRef = constPool.findOrAddClass(className).getIndex(constPool);
            emit(Opcode.ANEWARRAY.getCode());
            emitShort((short) classRef);
        }
    }

    private void emitFieldAccess(FieldAccessInstruction instr) throws IOException {
        int fieldRef = constPool.findOrAddFieldRef(
                instr.getOwner(), instr.getName(), instr.getDescriptor()
        ).getIndex(constPool);

        if (instr.isLoad()) {
            emit(instr.isStatic() ? Opcode.GETSTATIC.getCode() : Opcode.GETFIELD.getCode());
        } else {
            emit(instr.isStatic() ? Opcode.PUTSTATIC.getCode() : Opcode.PUTFIELD.getCode());
        }
        emitShort((short) fieldRef);
    }

    private void emitArrayAccess(ArrayAccessInstruction instr) throws IOException {
        if (instr.isLoad()) {
            IRType elemType = instr.getResult().getType();
            int opcode;
            if (elemType instanceof PrimitiveType) {
                PrimitiveType prim = (PrimitiveType) elemType;
                switch (prim) {
                    case INT:
                        opcode = Opcode.IALOAD.getCode();
                        break;
                    case LONG:
                        opcode = Opcode.LALOAD.getCode();
                        break;
                    case FLOAT:
                        opcode = Opcode.FALOAD.getCode();
                        break;
                    case DOUBLE:
                        opcode = Opcode.DALOAD.getCode();
                        break;
                    case BYTE:
                    case BOOLEAN:
                        opcode = Opcode.BALOAD.getCode();
                        break;
                    case CHAR:
                        opcode = Opcode.CALOAD.getCode();
                        break;
                    case SHORT:
                        opcode = Opcode.SALOAD.getCode();
                        break;
                    default:
                        throw new IllegalStateException("Unknown primitive type: " + prim);
                }
            } else {
                opcode = Opcode.AALOAD.getCode();
            }
            emit(opcode);
        } else {
            IRType elemType = instr.getValue().getType();
            int opcode;
            if (elemType instanceof PrimitiveType) {
                PrimitiveType prim = (PrimitiveType) elemType;
                switch (prim) {
                    case INT:
                        opcode = Opcode.IASTORE.getCode();
                        break;
                    case LONG:
                        opcode = Opcode.LASTORE.getCode();
                        break;
                    case FLOAT:
                        opcode = Opcode.FASTORE.getCode();
                        break;
                    case DOUBLE:
                        opcode = Opcode.DASTORE.getCode();
                        break;
                    case BYTE:
                    case BOOLEAN:
                        opcode = Opcode.BASTORE.getCode();
                        break;
                    case CHAR:
                        opcode = Opcode.CASTORE.getCode();
                        break;
                    case SHORT:
                        opcode = Opcode.SASTORE.getCode();
                        break;
                    default:
                        throw new IllegalStateException("Unknown primitive type: " + prim);
                }
            } else {
                opcode = Opcode.AASTORE.getCode();
            }
            emit(opcode);
        }
    }

    private void emitTypeCheck(TypeCheckInstruction instr) throws IOException {
        String typeName = instr.getTargetType().getDescriptor();
        if (typeName.startsWith("L") && typeName.endsWith(";")) {
            typeName = typeName.substring(1, typeName.length() - 1);
        }
        int classRef = constPool.findOrAddClass(typeName).getIndex(constPool);

        if (instr.isCast()) {
            emit(Opcode.CHECKCAST.getCode());
        } else {
            emit(Opcode.INSTANCEOF.getCode());
        }
        emitShort((short) classRef);
    }

    private void emitSimple(SimpleInstruction instr) throws IOException {
        switch (instr.getOp()) {
            case ARRAYLENGTH:
                emit(Opcode.ARRAYLENGTH.getCode());
                break;
            case MONITORENTER:
                emit(Opcode.MONITORENTER.getCode());
                break;
            case MONITOREXIT:
                emit(Opcode.MONITOREXIT.getCode());
                break;
            case ATHROW:
                emit(Opcode.ATHROW.getCode());
                break;
            case GOTO:
                if (instr.getTarget() != nextBlock) {
                    emit(Opcode.GOTO.getCode());
                    pendingJumps.add(new PendingJump(currentOffset, instr.getTarget(), false));
                    emitShort((short) 0);
                }
                break;
            case CATCH:
                // No opcode: the JVM already placed the caught exception on the stack at the handler
                // entry. emitResultStore turns this into an astore into the catch variable's slot (or
                // discards it into a dead slot if the variable is unused).
                break;
            default:
                throw new IllegalStateException("Unknown simple op: " + instr.getOp());
        }
    }

    private void emitSwitch(SwitchInstruction instr) throws IOException {
        Map<Integer, IRBlock> cases = instr.getCases();
        List<Integer> keys = new ArrayList<>(cases.keySet());
        Collections.sort(keys);

        if (keys.isEmpty()) {
            emit(Opcode.GOTO.getCode());
            pendingJumps.add(new PendingJump(currentOffset, instr.getDefaultTarget(), false));
            emitShort((short) 0);
            return;
        }

        int low = keys.get(0);
        int high = keys.get(keys.size() - 1);
        long tableSize = (long) high - (long) low + 1;
        boolean useTableSwitch = tableSize > 0 && tableSize <= keys.size() * 2L && tableSize <= 65536;

        int switchStart = currentOffset;
        if (useTableSwitch) {
            emit(Opcode.TABLESWITCH.getCode());
        } else {
            emit(Opcode.LOOKUPSWITCH.getCode());
        }

        while (currentOffset % 4 != 0) {
            emit(Opcode.NOP.getCode());
        }

        pendingJumps.add(new PendingJump(currentOffset, instr.getDefaultTarget(), true, switchStart));
        emitInt(0);

        if (useTableSwitch) {
            emitInt(low);
            emitInt(high);
            for (int key = low; key <= high; key++) {
                IRBlock target = cases.getOrDefault(key, instr.getDefaultTarget());
                pendingJumps.add(new PendingJump(currentOffset, target, true, switchStart));
                emitInt(0);
            }
        } else {
            emitInt(keys.size());
            for (int key : keys) {
                emitInt(key);
                pendingJumps.add(new PendingJump(currentOffset, cases.get(key), true, switchStart));
                emitInt(0);
            }
        }
    }

    /**
     * For phi copy values, returns the phi result's register slot.
     * Returns -1 if the value is not a phi copy.
     */
    private int getPhiCopyDestination(SSAValue copyValue) {
        Map<SSAValue, List<CopyInfo>> phiCopies = method.getPhiCopyMapping();
        if (phiCopies == null) return -1;

        for (Map.Entry<SSAValue, List<CopyInfo>> entry : phiCopies.entrySet()) {
            for (CopyInfo copyInfo : entry.getValue()) {
                if (copyInfo.copyValue().equals(copyValue)) {
                    return regAlloc.getRegister(entry.getKey());
                }
            }
        }
        return -1;
    }

    private void emitCopy(CopyInstruction instr) throws IOException {
        Value source = instr.getSource();

        int dstReg = getPhiCopyDestination(instr.getResult());
        if (dstReg < 0) {
            dstReg = regAlloc.getRegister(instr.getResult());
        }

        // Caught-exception capture: the JVM has placed the exception (a reference) on the handler-entry
        // stack. Store it into the exception value's local so later handler code can re-load it.
        if (source == instr.getResult() && handlerExceptionCaptures.contains(instr.getResult())) {
            emitVarInsn(Opcode.ASTORE.getCode(), Opcode.ASTORE_0.getCode(), dstReg);
            return;
        }

        if (source instanceof SSAValue) {
            SSAValue ssa = (SSAValue) source;
            if (stackResidentValues.contains(ssa)) {
                IRType type = ssa.getType();
                if (type instanceof PrimitiveType) {
                    PrimitiveType prim = (PrimitiveType) type;
                    switch (prim) {
                        case INT:
                        case BOOLEAN:
                        case BYTE:
                        case CHAR:
                        case SHORT:
                            emitVarInsn(Opcode.ISTORE.getCode(), Opcode.ISTORE_0.getCode(), dstReg);
                            break;
                        case LONG:
                            emitVarInsn(Opcode.LSTORE.getCode(), Opcode.LSTORE_0.getCode(), dstReg);
                            break;
                        case FLOAT:
                            emitVarInsn(Opcode.FSTORE.getCode(), Opcode.FSTORE_0.getCode(), dstReg);
                            break;
                        case DOUBLE:
                            emitVarInsn(Opcode.DSTORE.getCode(), Opcode.DSTORE_0.getCode(), dstReg);
                            break;
                    }
                } else {
                    emitVarInsn(Opcode.ASTORE.getCode(), Opcode.ASTORE_0.getCode(), dstReg);
                }
            } else {
                int srcReg = regAlloc.getRegister(ssa);
                if (srcReg != dstReg) {
                    IRType type = ssa.getType();
                    emitVarInsn(getLoadOpcode(type), getLoadShortBase(type), srcReg);
                    emitVarInsn(getStoreOpcode(type), getStoreShortBase(type), dstReg);
                }
            }
        } else if (source instanceof Constant) {
            Constant constant = (Constant) source;
            emitConstantValue(constant);
            IRType type = constant.getType();
            if (type instanceof PrimitiveType) {
                PrimitiveType prim = (PrimitiveType) type;
                switch (prim) {
                    case INT:
                    case BOOLEAN:
                    case BYTE:
                    case CHAR:
                    case SHORT:
                        emitVarInsn(Opcode.ISTORE.getCode(), Opcode.ISTORE_0.getCode(), dstReg);
                        break;
                    case LONG:
                        emitVarInsn(Opcode.LSTORE.getCode(), Opcode.LSTORE_0.getCode(), dstReg);
                        break;
                    case FLOAT:
                        emitVarInsn(Opcode.FSTORE.getCode(), Opcode.FSTORE_0.getCode(), dstReg);
                        break;
                    case DOUBLE:
                        emitVarInsn(Opcode.DSTORE.getCode(), Opcode.DSTORE_0.getCode(), dstReg);
                        break;
                }
            } else {
                emitVarInsn(Opcode.ASTORE.getCode(), Opcode.ASTORE_0.getCode(), dstReg);
            }
        }
    }

    private int getLoadOpcode(IRType type) {
        if (type instanceof PrimitiveType) {
            PrimitiveType prim = (PrimitiveType) type;
            switch (prim) {
                case INT:
                case BOOLEAN:
                case BYTE:
                case CHAR:
                case SHORT:
                    return Opcode.ILOAD.getCode();
                case LONG:
                    return Opcode.LLOAD.getCode();
                case FLOAT:
                    return Opcode.FLOAD.getCode();
                case DOUBLE:
                    return Opcode.DLOAD.getCode();
            }
        }
        return Opcode.ALOAD.getCode();
    }

    private int getLoadShortBase(IRType type) {
        if (type instanceof PrimitiveType) {
            PrimitiveType prim = (PrimitiveType) type;
            switch (prim) {
                case INT:
                case BOOLEAN:
                case BYTE:
                case CHAR:
                case SHORT:
                    return Opcode.ILOAD_0.getCode();
                case LONG:
                    return Opcode.LLOAD_0.getCode();
                case FLOAT:
                    return Opcode.FLOAD_0.getCode();
                case DOUBLE:
                    return Opcode.DLOAD_0.getCode();
            }
        }
        return Opcode.ALOAD_0.getCode();
    }

    private int getStoreOpcode(IRType type) {
        if (type instanceof PrimitiveType) {
            PrimitiveType prim = (PrimitiveType) type;
            switch (prim) {
                case INT:
                case BOOLEAN:
                case BYTE:
                case CHAR:
                case SHORT:
                    return Opcode.ISTORE.getCode();
                case LONG:
                    return Opcode.LSTORE.getCode();
                case FLOAT:
                    return Opcode.FSTORE.getCode();
                case DOUBLE:
                    return Opcode.DSTORE.getCode();
            }
        }
        return Opcode.ASTORE.getCode();
    }

    private int getStoreShortBase(IRType type) {
        if (type instanceof PrimitiveType) {
            PrimitiveType prim = (PrimitiveType) type;
            switch (prim) {
                case INT:
                case BOOLEAN:
                case BYTE:
                case CHAR:
                case SHORT:
                    return Opcode.ISTORE_0.getCode();
                case LONG:
                    return Opcode.LSTORE_0.getCode();
                case FLOAT:
                    return Opcode.FSTORE_0.getCode();
                case DOUBLE:
                    return Opcode.DSTORE_0.getCode();
            }
        }
        return Opcode.ASTORE_0.getCode();
    }

    private int createInvokeDynamicEntry(InvokeInstruction instr) {
        BootstrapMethodInfo bsInfo = instr.getBootstrapInfo();
        if (bsInfo == null) {
            throw new IllegalStateException("No bootstrap info for INVOKEDYNAMIC: " + instr.getName());
        }

        ClassFile classFile = constPool.getClassFile();
        if (classFile == null) {
            throw new IllegalStateException("No ClassFile available for creating INVOKEDYNAMIC entry");
        }

        BootstrapMethodsAttribute bsmAttr = findOrCreateBootstrapMethodsAttribute(classFile);

        MethodHandleConstant mh = bsInfo.getBootstrapMethod();
        int methodHandleIndex = constPool.findOrAddMethodHandle(
            mh.getReferenceKind(),
            mh.getOwner(),
            mh.getName(),
            mh.getDescriptor()
        ).getIndex(constPool);

        List<Integer> bsArgIndices = new ArrayList<>();
        for (Constant arg : bsInfo.getBootstrapArguments()) {
            int argIndex = addConstantToPool(arg);
            bsArgIndices.add(argIndex);
        }

        bsmAttr.addBootstrapMethod(methodHandleIndex, bsArgIndices);
        int bootstrapMethodIndex = bsmAttr.getBootstrapMethods().size() - 1;

        int nameAndTypeIndex = constPool.addNameAndType(instr.getName(), instr.getDescriptor());

        return constPool.addInvokeDynamic(bootstrapMethodIndex, nameAndTypeIndex);
    }

    private BootstrapMethodsAttribute findOrCreateBootstrapMethodsAttribute(ClassFile classFile) {
        for (Attribute attr : classFile.getClassAttributes()) {
            if (attr instanceof BootstrapMethodsAttribute) {
                return (BootstrapMethodsAttribute) attr;
            }
        }
        BootstrapMethodsAttribute bsmAttr = new BootstrapMethodsAttribute(constPool);
        classFile.getClassAttributes().add(bsmAttr);
        return bsmAttr;
    }

    private int addConstantToPool(Constant constant) {
        if (constant instanceof StringConstant) {
            return constPool.findOrAddString(((StringConstant) constant).getValue()).getIndex(constPool);
        } else if (constant instanceof IntConstant) {
            return constPool.findOrAddInteger(((IntConstant) constant).getValue()).getIndex(constPool);
        } else if (constant instanceof LongConstant) {
            return constPool.findOrAddLong(((LongConstant) constant).getValue()).getIndex(constPool);
        } else if (constant instanceof FloatConstant) {
            return constPool.findOrAddFloat(((FloatConstant) constant).getValue()).getIndex(constPool);
        } else if (constant instanceof DoubleConstant) {
            return constPool.findOrAddDouble(((DoubleConstant) constant).getValue()).getIndex(constPool);
        } else if (constant instanceof MethodHandleConstant) {
            MethodHandleConstant mh = (MethodHandleConstant) constant;
            return constPool.findOrAddMethodHandle(
                mh.getReferenceKind(),
                mh.getOwner(),
                mh.getName(),
                mh.getDescriptor()
            ).getIndex(constPool);
        } else if (constant instanceof MethodTypeConstant) {
            MethodTypeConstant mt = (MethodTypeConstant) constant;
            return constPool.addMethodType(mt.getDescriptor());
        } else if (constant instanceof ClassConstant) {
            return constPool.findOrAddClass(((ClassConstant) constant).getClassName()).getIndex(constPool);
        } else {
            throw new IllegalArgumentException("Unsupported bootstrap argument type: " + constant.getClass().getName());
        }
    }

    private void fixupJumps() {
        byte[] code = bytecode.toByteArray();
        for (PendingJump jump : pendingJumps) {
            int targetOffset = blockOffsets.getOrDefault(jump.target(), 0);
            int relativeOffset = targetOffset - jump.baseOffset();

            if (jump.isWide()) {
                code[jump.offset()] = (byte) (relativeOffset >> 24);
                code[jump.offset() + 1] = (byte) (relativeOffset >> 16);
                code[jump.offset() + 2] = (byte) (relativeOffset >> 8);
                code[jump.offset() + 3] = (byte) relativeOffset;
            } else {
                // Check for overflow - offset must fit in signed 16-bit
                if (relativeOffset < Short.MIN_VALUE || relativeOffset > Short.MAX_VALUE) {
                    throw new IllegalStateException(
                        "Branch offset " + relativeOffset + " exceeds 16-bit range. " +
                        "Method is too large and requires wide branch instructions (goto_w).");
                }
                code[jump.offset()] = (byte) (relativeOffset >> 8);
                code[jump.offset() + 1] = (byte) relativeOffset;
            }
        }
        bytecode = new ByteArrayOutputStream();
        try {
            bytecode.write(code);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private void emit(int b) throws IOException {
        dos.writeByte(b);
        currentOffset++;
    }

    private void emitShort(short s) throws IOException {
        dos.writeShort(s);
        currentOffset += 2;
    }

    private void emitInt(int i) throws IOException {
        dos.writeInt(i);
        currentOffset += 4;
    }

    private int migrateBootstrapMethod(DynamicConstant dynConst) {
        MethodEntry sourceMethod = method.getSourceMethod();
        if (sourceMethod == null) {
            return dynConst.getBootstrapMethodIndex();
        }

        ClassFile sourceClass = sourceMethod.getClassFile();
        if (sourceClass == null) {
            return dynConst.getBootstrapMethodIndex();
        }

        ClassFile targetClass = constPool.getClassFile();
        if (targetClass == null || sourceClass == targetClass) {
            return dynConst.getBootstrapMethodIndex();
        }

        BootstrapMethodsAttribute sourceBsmAttr = findBootstrapMethodsAttribute(sourceClass);
        if (sourceBsmAttr == null) {
            return dynConst.getBootstrapMethodIndex();
        }

        List<BootstrapMethod> sourceBsms = sourceBsmAttr.getBootstrapMethods();
        int bsmIndex = dynConst.getBootstrapMethodIndex();
        if (bsmIndex < 0 || bsmIndex >= sourceBsms.size()) {
            return bsmIndex;
        }

        BootstrapMethod sourceBsm = sourceBsms.get(bsmIndex);
        ConstPool sourceCP = sourceClass.getConstPool();

        int newMethodHandleIndex = migrateConstantPoolItem(sourceCP, sourceBsm.getBootstrapMethodRef());

        List<Integer> newArguments = new ArrayList<>();
        for (int argIndex : sourceBsm.getBootstrapArguments()) {
            newArguments.add(migrateConstantPoolItem(sourceCP, argIndex));
        }

        BootstrapMethodsAttribute targetBsmAttr = findOrCreateBootstrapMethodsAttribute(targetClass);
        targetBsmAttr.addBootstrapMethod(newMethodHandleIndex, newArguments);

        return targetBsmAttr.getBootstrapMethods().size() - 1;
    }

    private int migrateConstantPoolItem(ConstPool sourceCP, int sourceIndex) {
        Item<?> item = sourceCP.getItem(sourceIndex);
        if (item == null) {
            return sourceIndex;
        }

        if (item instanceof IntegerItem) {
            int value = ((IntegerItem) item).getValue();
            return constPool.findOrAddInteger(value).getIndex(constPool);
        } else if (item instanceof LongItem) {
            long value = ((LongItem) item).getValue();
            return constPool.findOrAddLong(value).getIndex(constPool);
        } else if (item instanceof FloatItem) {
            float value = ((FloatItem) item).getValue();
            return constPool.findOrAddFloat(value).getIndex(constPool);
        } else if (item instanceof DoubleItem) {
            double value = ((DoubleItem) item).getValue();
            return constPool.findOrAddDouble(value).getIndex(constPool);
        } else if (item instanceof StringRefItem) {
            Utf8Item utf8 = (Utf8Item) sourceCP.getItem(((StringRefItem) item).getValue());
            return constPool.findOrAddString(utf8.getValue()).getIndex(constPool);
        } else if (item instanceof ClassRefItem) {
            Utf8Item utf8 = (Utf8Item) sourceCP.getItem(((ClassRefItem) item).getValue());
            return constPool.findOrAddClass(utf8.getValue()).getIndex(constPool);
        } else if (item instanceof MethodTypeItem) {
            int descIndex = ((MethodTypeItem) item).getValue();
            Utf8Item descUtf8 = (Utf8Item) sourceCP.getItem(descIndex);
            return constPool.findOrAddMethodType(descUtf8.getValue()).getIndex(constPool);
        } else if (item instanceof MethodHandleItem) {
            MethodHandleItem mhItem = (MethodHandleItem) item;
            int refKind = mhItem.getValue().getReferenceKind();
            int refIndex = mhItem.getValue().getReferenceIndex();
            Item<?> refItem = sourceCP.getItem(refIndex);

            String owner, name, desc;
            if (refItem instanceof FieldRefItem) {
                FieldRefItem fieldRef = (FieldRefItem) refItem;
                owner = resolveClassName(sourceCP, fieldRef.getValue().getClassIndex());
                int natIndex = fieldRef.getValue().getNameAndTypeIndex();
                NameAndTypeRefItem nat = (NameAndTypeRefItem) sourceCP.getItem(natIndex);
                name = ((Utf8Item) sourceCP.getItem(nat.getValue().getNameIndex())).getValue();
                desc = ((Utf8Item) sourceCP.getItem(nat.getValue().getDescriptorIndex())).getValue();
            } else if (refItem instanceof MethodRefItem) {
                MethodRefItem methodRef = (MethodRefItem) refItem;
                owner = resolveClassName(sourceCP, methodRef.getValue().getClassIndex());
                int natIndex = methodRef.getValue().getNameAndTypeIndex();
                NameAndTypeRefItem nat = (NameAndTypeRefItem) sourceCP.getItem(natIndex);
                name = ((Utf8Item) sourceCP.getItem(nat.getValue().getNameIndex())).getValue();
                desc = ((Utf8Item) sourceCP.getItem(nat.getValue().getDescriptorIndex())).getValue();
            } else if (refItem instanceof InterfaceRefItem) {
                InterfaceRefItem ifaceRef = (InterfaceRefItem) refItem;
                owner = resolveClassName(sourceCP, ifaceRef.getValue().getClassIndex());
                int natIndex = ifaceRef.getValue().getNameAndTypeIndex();
                NameAndTypeRefItem nat = (NameAndTypeRefItem) sourceCP.getItem(natIndex);
                name = ((Utf8Item) sourceCP.getItem(nat.getValue().getNameIndex())).getValue();
                desc = ((Utf8Item) sourceCP.getItem(nat.getValue().getDescriptorIndex())).getValue();
            } else {
                return sourceIndex;
            }

            return constPool.findOrAddMethodHandle(refKind, owner, name, desc).getIndex(constPool);
        } else if (item instanceof ConstantDynamicItem) {
            ConstantDynamicItem cdItem = (ConstantDynamicItem) item;
            String name = cdItem.getName();
            String desc = cdItem.getDescriptor();
            int bsmIndex = cdItem.getBootstrapMethodAttrIndex();
            return constPool.findOrAddConstantDynamic(bsmIndex, name, desc).getIndex(constPool);
        }

        return sourceIndex;
    }

    private String resolveClassName(ConstPool cp, int classIndex) {
        ClassRefItem classRef = (ClassRefItem) cp.getItem(classIndex);
        Utf8Item utf8 = (Utf8Item) cp.getItem(classRef.getValue());
        return utf8.getValue();
    }

    private BootstrapMethodsAttribute findBootstrapMethodsAttribute(ClassFile classFile) {
        for (Attribute attr : classFile.getClassAttributes()) {
            if (attr instanceof BootstrapMethodsAttribute) {
                return (BootstrapMethodsAttribute) attr;
            }
        }
        return null;
    }

    private static final class PendingJump {
        private final int offset;
        private final IRBlock target;
        private final boolean isWide;
        private final int baseOffset;

        public PendingJump(int offset, IRBlock target, boolean isWide) {
            this.offset = offset;
            this.target = target;
            this.isWide = isWide;
            this.baseOffset = offset - 1;
        }

        public PendingJump(int offset, IRBlock target, boolean isWide, int baseOffset) {
            this.offset = offset;
            this.target = target;
            this.isWide = isWide;
            this.baseOffset = baseOffset;
        }

        public int offset() {
            return offset;
        }

        public IRBlock target() {
            return target;
        }

        public boolean isWide() {
            return isWide;
        }

        public int baseOffset() {
            return baseOffset;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) return true;
            if (obj == null || getClass() != obj.getClass()) return false;
            PendingJump that = (PendingJump) obj;
            return offset == that.offset &&
                   isWide == that.isWide &&
                   Objects.equals(target, that.target);
        }

        @Override
        public int hashCode() {
            return Objects.hash(offset, target, isWide);
        }

        @Override
        public String toString() {
            return "PendingJump{" +
                   "offset=" + offset +
                   ", target=" + target +
                   ", isWide=" + isWide +
                   '}';
        }
    }
}
