package com.tonic.testutil;

/**
 * Custom class loader for loading dynamically generated classes in tests.
 * Allows verification that generated bytecode is valid and loadable by the JVM.
 */
public class TestClassLoader extends ClassLoader {

    /**
     * Creates a new TestClassLoader with the system class loader as parent.
     */
    public TestClassLoader() {
        super(TestClassLoader.class.getClassLoader());
    }

    /**
     * Creates a new TestClassLoader with the specified parent.
     *
     * @param parent the parent class loader
     */
    public TestClassLoader(ClassLoader parent) {
        super(parent);
    }

    /**
     * Defines a class from raw bytes.
     *
     * @param name the fully qualified class name (e.g., "com.test.MyClass")
     * @param bytes the class file bytes
     * @return the defined Class
     */
    public Class<?> defineClass(String name, byte[] bytes) {
        return defineClass(name, bytes, 0, bytes.length);
    }

    /**
     * Loads a class, attempting to define it if not already loaded.
     *
     * @param name the fully qualified class name
     * @param bytes the class file bytes
     * @return the loaded Class
     * @throws ClassNotFoundException if loading fails
     */
    public Class<?> loadAndDefine(String name, byte[] bytes) throws ClassNotFoundException {
        try {
            return loadClass(name);
        } catch (ClassNotFoundException e) {
            return defineClass(name, bytes);
        }
    }

    /**
     * Defines multiple classes at once. Useful for classes with dependencies.
     *
     * @param classes array of [name, bytes] pairs
     * @return array of defined Classes
     */
    public Class<?>[] defineClasses(Object[][] classes) {
        Class<?>[] result = new Class<?>[classes.length];
        for (int i = 0; i < classes.length; i++) {
            String name = (String) classes[i][0];
            byte[] bytes = (byte[]) classes[i][1];
            result[i] = defineClass(name, bytes);
        }
        return result;
    }
}
