package com.tonic.parser.attribute;

import com.tonic.parser.ClassFile;
import com.tonic.parser.MemberEntry;

import java.io.DataOutputStream;
import java.io.IOException;

/**
 * Represents the Synthetic attribute.
 * Indicates that the annotated element was generated by the compiler.
 */
public class SyntheticAttribute extends Attribute {

    public SyntheticAttribute(String name, MemberEntry parent, int nameIndex, int length) {
        super(name, parent, nameIndex, length);
    }

    @Override
    public void read(ClassFile classFile, int length) {
        if (length != 0) {
            throw new IllegalArgumentException("Synthetic attribute length must be 0, found: " + length);
        }
        // No additional data to read
    }

    @Override
    protected void writeInfo(DataOutputStream dos) throws IOException {
        // No additional info
    }

    @Override
    public void updateLength() {
        this.length = 0;
    }


    @Override
    public String toString() {
        return "SyntheticAttribute{}";
    }
}
